on:
  workflow_dispatch:
  pull_request:

jobs:
  echo_event:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

        
      - name: test
        run: |
          echo 'The event is: ${{ github.actor }}' > test.txt

      - name: commmit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated change
          
