on:
  workflow_dispatch:
  pull_request:

jobs:
  echo_event:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          echo The event is: PR_${{ github.actor }}_${{ github.event.number }}
    
