on:
    workflow_dispatch:

jobs:
    test_job:
        strategy:
            matrix: 
                test: [test_1, test_2]
        runs-on: ubuntu-latest
        env:
            TEST: ${{ matrix.test }}

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Run test
              run: |
                echo $TEST