on:
    release:
        types: [published]

jobs:
    test:
        runs-on: ubuntu-latest
        
        steps:
            - name: echo
              run: |
                pwd
                ls
