on:
    release:
        types: [published]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
        
            - name: echo
              run: |
                  pwd
                  ls
