name: My Hello world workflow

on:
  workflow_dispatch

jobs:
  say_hello:
    name: Say hello to someone
    runs-on: ubuntu-latest

    steps:
      - name: Say it
        run: echo "Hello tom"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies  
        run: pip install pytest pytest-html build

      - name: FInd files
        run: |
          pwd
          ls

      - name: run tests
        run: pytest src -v

      - name: Build package
        run: python3 -m build

      - name: Upload packaged project
        uses: actions/upload-artifact@v4
        with: 
          name: my_artifact
          overwrite: True

  download-package:
    name: Download the package
    runs-on: ubuntu-latest

    steps:
      name: Download the artifact
      uses: actions/download-artifact@v4
      with:
        name: my_artifact
        