name: My Hello world workflow

on:
  workflow_dispatch

jobs:
  say_hello:
    name: Say hello to someone
    runs-on: ubuntu-latest

    steps:
      - name: Say it
        run: echo "Hello tom"

      - name: Install dependencies  
        run: pip install pytest pytest-html

      - name: run tests
        run: pytest src -v